# -*- coding: utf-8 -*-
"""dice rolling simulation.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u7mxG-3u4bOB7yBShY9racbHhG9ZmoAs
"""

import random

roll_agian = input("roll the dice (yes/y or no/n)")

while roll_agian== 'y'or roll_agian=='yes':
  a = random.randint(1,6)
  print ("your dice number is :" ,"\n",a)
  
  roll_agian=input("roll the dice ???(yes for y no for n)")

print("thank you ")